[main]
    separator = "-"
    description = "Hinode is a clean documentation and blog theme for your Hugo site based on Bootstrap 5."
    enableLanguageSelectionStorage = false
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    titleCase = false # keep this false to avoid issues with inline code in headings
    [main.colorMode]
        enabled = true
        modes = ["light", "dark"]
        toggle = false
    [main.internalLinks]
        validate = true
        pretty = false
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "dartsass"

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = true

[docs]
    github = "https://github.com/cedadev/ceda-div-hugo-hinode"
    #release = "https://github.com/gethinode/hinode/releases/tag/"
    checkVersion = false

[home]
    fullCover = false
    centerHeadline = false
    style = ""

[navigation]
    anchor = true
    logo = "/img/logos/ceda-logo-light.png"
    color = "body-tertiary"
    fixed = true
    overlay = false #
    overlayMode = "dark" #
    horizontal = false #
    offset = "5.5rem"
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
    logo-height = 80
    [navigation.search]
        enabled = true
        modal = true
    [navigation.padding]
        x = 1
        y = 1

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 40

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

[[sharing.providers]]
    name = "custom link"
    url = "[{title}]({url})"
    icon = "fas star"
    title = "custom link"
    weight = 60
    clipboard = true

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#446E9B"
    secondary = "#999999"
    success = "#3CB521"
    info = "#3399F3"
    warning = "#D47500"
    danger = "#CD0200"
    light = "#EEEEEE"
    dark = "#333333"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Lato"
    themeFontPath = "https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400&display=swap" # external path
    #themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem"

[schema]
    type = "Organization"
    name = "CEDA"
    locale = "en-GB"
    github = "https://github.com/cedadev"
    #section = "news"
    [schema.author]
        name = "Matt Pritchard"
    [schema.logo]
        url = "img/logos/ceda-logo-whitebg-small.png?source=schema.logo"
        width = 48
        height = 48
    [schema.image]
        url = "img/logos/ceda-logo-whitebg-small.png?source=schema.image"
        width = 48
        height = 48

[opengraph]
    images = ["img/logos/ceda-logo-whitebg-small.png?source=opengraph"]
    locale = "en_GB"

[links]
    hinode = "https://gethinode.com"
    ceda_site = "/"
    ceda_archive = "https://archive.ceda.ac.uk"
    ceda_catalogue = "https://catalogue.ceda.ac.uk"
    ceda_helpdocs = "https://help.ceda.ac.uk"
    ceda_helpdesk = "https://help.ceda.ac.uk"
    ceda_status = "/status"
    ceda_contact = "/contact"
    nceo = "https://www.nceo.ac.uk"
    ncas = "https://www.ncas.ac.uk"
    jasmin = "https://www.jasmin.ac.uk"
    stfc = "https://stfc.ukri.org"
    nerc = "https://nerc.ukri.org"
    ukri = "https://ukri.org"

[statusClasses]
    "down" = "danger"
    "resolved" = "success"
    "degraded" = "warning"
    "at risk" = "dark"

[statusData]
    # URL for publicly-shared CSV view of Google Sheet with CEDA status updates
    "sourceURL" = "https://cedadev.github.io/ceda-status/status.json"
    "viewURL" = "https://github.com/cedadev/ceda-status/blob/main/status.json"

